name: Deploy React App to AWS

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: ./client

    - name: Build
      run: npm run build
      working-directory: ./client

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ap-southeast-1'

    - name: Sync to S3
      run: aws s3 sync build/ s3://g2t4-ocbc-frontend-ap-es-1 --delete
      working-directory: ./client

    - name: Invalidate CloudFront distribution
      run: aws cloudfront create-invalidation --distribution-id 'E28B7ZXFGHFMBX' --paths "/*"
      working-directory: ./client
